
server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: THEATRE-SERVICE
          uri: lb://THEATRE-SERVICE
          predicates:
            - Path=/theatre/**

        - id: TICKET-SERVICE
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9005/eureka


